[lab]
lab ansible_host=192.168.1.3

[gateway]
gateway ansible_host=192.168.1.1

[unifi]
unifi ansible_host=192.168.1.2

[pi]
pihole2 ansible_host=192.168.1.251

[rhel]
rhel8  ansible_host=192.168.1.35
rhel9  ansible_host=192.168.1.36

[ol]
ol9  ansible_host=192.168.1.39
