---
- name: Configure Raspberry Pi
  hosts: pi
  become: true
  gather_facts: true
  roles:
    - { role: rpi-network, tags: rpi-network }
    - { role: podman,      tags: podman }
    - { role: pihole,        tags: pihole }
    - { role: node-exporter, tags: node-exporter }
